name: Resume Generation
on: push

jobs:
    upload_to_drive:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v2

            - name: Clean up LaTeX build files
              run: |
                  rm -rf *.aux *.bbl *.blg *.log *.out *.toc

            - name: Cache LaTeX build files
              id: cache-latex
              uses: actions/cache@v2
              with:
                path: |
                  ~/.texlive
                  ./build
                key: ${{ runner.os }}-latex-${{ hashFiles('**/*.tex') }}
                restore-keys: |
                  ${{ runner.os }}-latex-

            # - name: Install LaTeX
            #   run: |
            #     sudo apt-get update
            #     sudo apt-get install -y texlive-full

            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: resume.tex
                  latexmk_use_xelatex: true

            - name: Extract branch name
              shell: bash
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
              id: extract_branch

            - name: Make Directory Structure
              run: |
                  mkdir -p ${{ steps.extract_branch.outputs.branch }}
                  mv resume.pdf ${{ steps.extract_branch.outputs.branch }}/

            - name: Upload file to Google Drive
              uses: adityak74/google-drive-upload-git-action@main
              with:
                  credentials: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
                  filename: ${{ steps.extract_branch.outputs.branch }}/resume.pdf
                  folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
                  overwrite: "true"
                  mirrorDirectoryStructure: "true"
